on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go: [1.13.x, 1.14.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Dependencies
        run: |
          apt-get update
          apt-get install -y build-essential
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - name: Checkout code
        uses: "actions/checkout@v2"
      - name: Test
        run: go test ./...

  test-gopath:
    env:
      GOPATH: ${{ github.workspace }}
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          apt-get update
          apt-get install -y build-essential git
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.x
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ./src/github.com/${{ github.repository }}
      - name: Test
        run: |
          go get -d -v -t ./...
          go test ./...